export const dailyAllowances = [
	{ name: 'Afganistan', allowance: 59, icon: '🇦🇫' },
	{ name: 'Alankomaat', allowance: 83, icon: '🇳🇱' },
	{ name: 'Albania', allowance: 81, icon: '🇦🇱' },
	{ name: 'Algeria', allowance: 78, icon: '🇩🇿' },
	{ name: 'Andorra', allowance: 63, icon: '🇦🇩' },
	{ name: 'Angola', allowance: 71, icon: '🇦🇴' },
	{ name: 'Antigua ja Barbuda', allowance: 94, icon: '🇦🇬' },
	{ name: 'Arabiemiirikunnat', allowance: 73, icon: '🇦🇪' },
	{ name: 'Argentiina', allowance: 38, icon: '🇦🇷' },
	{ name: 'Armenia', allowance: 61, icon: '🇦🇲' },
	{ name: 'Aruba', allowance: 70, icon: '🇦🇼' },
	{ name: 'Australia', allowance: 74, icon: '🇦🇺' },
	{ name: 'Azerbaidžan', allowance: 70, icon: '🇦🇿' },
	{ name: 'Azorit', allowance: 69, icon: '🇵🇹' },
	{ name: 'Bahama', allowance: 91, icon: '🇧🇸' },
	{ name: 'Bahrain', allowance: 80, icon: '🇧🇭' },
	{ name: 'Bangladesh', allowance: 57, icon: '🇧🇩' },
	{ name: 'Barbados', allowance: 83, icon: '🇧🇧' },
	{ name: 'Belgia', allowance: 77, icon: '🇧🇪' },
	{ name: 'Belize', allowance: 52, icon: '🇧🇿' },
	{ name: 'Benin', allowance: 47, icon: '🇧🇯' },
	{ name: 'Bermuda', allowance: 90, icon: '🇧🇲' },
	{ name: 'Bhutan', allowance: 49, icon: '🇧🇹' },
	{ name: 'Bolivia', allowance: 48, icon: '🇧🇴' },
	{ name: 'Bosnia ja Hertsegovina', allowance: 54, icon: '🇧🇦' },
	{ name: 'Botswana', allowance: 41, icon: '🇧🇼' },
	{ name: 'Brasilia', allowance: 80, icon: '🇧🇷' },
	{ name: 'Britannia', allowance: 79, icon: '🇬🇧' },
	{ name: 'Brunei', allowance: 45, icon: '🇧🇳' },
	{ name: 'Bulgaria', allowance: 64, icon: '🇧🇬' },
	{ name: 'Burkina Faso', allowance: 40, icon: '🇧🇫' },
	{ name: 'Burundi', allowance: 46, icon: '🇧🇮' },
	{ name: 'Chile', allowance: 56, icon: '🇨🇱' },
	{ name: 'Cookinsaaret', allowance: 70, icon: '🇨🇰' },
	{ name: 'Costa Rica', allowance: 65, icon: '🇨🇷' },
	{ name: 'Curaçao', allowance: 58, icon: '🇨🇼' },
	{ name: 'Djibouti', allowance: 83, icon: '🇩🇯' },
	{ name: 'Dominica', allowance: 61, icon: '🇩🇲' },
	{ name: 'Dominikaaninen tasavalta', allowance: 53, icon: '🇩🇴' },
	{ name: 'Ecuador', allowance: 63, icon: '🇪🇨' },
	{ name: 'Egypti', allowance: 66, icon: '🇪🇬' },
	{ name: 'El Salvador', allowance: 60, icon: '🇸🇻' },
	{ name: 'Eritrea', allowance: 95, icon: '🇪🇷' },
	{ name: 'Espanja', allowance: 74, icon: '🇪🇸' },
	{ name: 'Eswatini', allowance: 37, icon: '🇸🇿' },
	{ name: 'Etelä-Afrikka', allowance: 50, icon: '🇿🇦' },
	{ name: 'Etelä-Sudan', allowance: 102, icon: '🇸🇸' },
	{ name: 'Etiopia', allowance: 49, icon: '🇪🇹' },
	{ name: 'Fidži', allowance: 52, icon: '🇫🇯' },
	{ name: 'Filippiinit', allowance: 69, icon: '🇵🇭' },
	{ name: 'Färsaaret', allowance: 61, icon: '🇫🇴' },
	{ name: 'Gabon', allowance: 92, icon: '🇬🇦' },
	{ name: 'Gambia', allowance: 46, icon: '🇬🇲' },
	{ name: 'Georgia', allowance: 49, icon: '🇬🇪' },
	{ name: 'Ghana', allowance: 47, icon: '🇬🇭' },
	{ name: 'Grenada', allowance: 73, icon: '🇬🇩' },
	{ name: 'Grönlanti', allowance: 63, icon: '🇬🇱' },
	{ name: 'Guadeloupe', allowance: 53, icon: '🇬🇵' },
	{ name: 'Guatemala', allowance: 76, icon: '🇬🇹' },
	{ name: 'Guinea', allowance: 83, icon: '🇬🇳' },
	{ name: 'Guinea-Bissau', allowance: 41, icon: '🇬🇼' },
	{ name: 'Guyana', allowance: 51, icon: '🇬🇾' },
	{ name: 'Haiti', allowance: 62, icon: '🇭🇹' },
	{ name: 'Honduras', allowance: 58, icon: '🇭🇳' },
	{ name: 'Indonesia', allowance: 57, icon: '🇮🇩' },
	{ name: 'Intia', allowance: 62, icon: '🇮🇳' },
	{ name: 'Irak', allowance: 70, icon: '🇮🇶' },
	{ name: 'Iran', allowance: 102, icon: '🇮🇷' },
	{ name: 'Irlanti', allowance: 78, icon: '🇮🇪' },
	{ name: 'Islanti', allowance: 92, icon: '🇮🇸' },
	{ name: 'Israel', allowance: 88, icon: '🇮🇱' },
	{ name: 'Italia', allowance: 76, icon: '🇮🇹' },
	{ name: 'Itä-Timor', allowance: 46, icon: '🇹🇱' },
	{ name: 'Itävalta', allowance: 80, icon: '🇦🇹' },
	{ name: 'Jamaika', allowance: 62, icon: '🇯🇲' },
	{ name: 'Japani', allowance: 66, icon: '🇯🇵' },
	{ name: 'Jemen', allowance: 102, icon: '🇾🇪' },
	{ name: 'Jordania', allowance: 90, icon: '🇯🇴' },
	{ name: 'Kambodža', allowance: 67, icon: '🇰🇭' },
	{ name: 'Kamerun', allowance: 59, icon: '🇨🇲' },
	{ name: 'Kanada', allowance: 82, icon: '🇨🇦' },
	{ name: 'Kanariansaaret', allowance: 71, icon: '🇮🇨' },
	{ name: 'Kap Verde', allowance: 45, icon: '🇨🇻' },
	{ name: 'Kazakstan', allowance: 59, icon: '🇰🇿' },
	{ name: 'Kenia', allowance: 70, icon: '🇰🇪' },
	{ name: 'Keski-Afrikan tasavalta', allowance: 101, icon: '🇨🇫' },
	{ name: 'Kiina', allowance: 74, icon: '🇨🇳' },
	{ name: 'Hongkong', allowance: 86, icon: '🇭🇰' },
	{ name: 'Kirgisia', allowance: 41, icon: '🇰🇬' },
	{ name: 'Kolumbia', allowance: 64, icon: '🇨🇴' },
	{ name: 'Komorit', allowance: 42, icon: '🇰🇲' },
	{ name: 'Kongo', allowance: 64, icon: '🇨🇬' },
	{ name: 'Kongon demokraattinen tasavalta', allowance: 51, icon: '🇨🇩' },
	{ name: 'Korean demokraattinen kansantasavalta', allowance: 70, icon: '🇰🇵' },
	{ name: 'Korean tasavalta', allowance: 87, icon: '🇰🇷' },
	{ name: 'Kosovo', allowance: 58, icon: '🇽🇰' },
	{ name: 'Kreikka', allowance: 68, icon: '🇬🇷' },
	{ name: 'Kroatia', allowance: 69, icon: '🇭🇷' },
	{ name: 'Kuuba', allowance: 68, icon: '🇨🇺' },
	{ name: 'Kuwait', allowance: 84, icon: '🇰🇼' },
	{ name: 'Kypros', allowance: 65, icon: '🇨🇾' },
	{ name: 'Laos', allowance: 32, icon: '🇱🇦' },
	{ name: 'Latvia', allowance: 73, icon: '🇱🇻' },
	{ name: 'Lesotho', allowance: 34, icon: '🇱🇸' },
	{ name: 'Libanon', allowance: 102, icon: '🇱🇧' },
	{ name: 'Liberia', allowance: 60, icon: '🇱🇷' },
	{ name: 'Libya', allowance: 52, icon: '🇱🇾' },
	{ name: 'Liechtenstein', allowance: 79, icon: '🇱🇮' },
	{ name: 'Liettua', allowance: 72, icon: '🇱🇹' },
	{ name: 'Luxemburg', allowance: 77, icon: '🇱🇺' },
	{ name: 'Madagaskar', allowance: 45, icon: '🇲🇬' },
	{ name: 'Madeira', allowance: 68, icon: '🇵🇹' },
	{ name: 'Malawi', allowance: 77, icon: '🇲🇼' },
	{ name: 'Malediivit', allowance: 68, icon: '🇲🇻' },
	{ name: 'Malesia', allowance: 50, icon: '🇲🇾' },
	{ name: 'Mali', allowance: 47, icon: '🇲🇱' },
	{ name: 'Malta', allowance: 71, icon: '🇲🇹' },
	{ name: 'Marokko', allowance: 71, icon: '🇲🇦' },
	{ name: 'Marshallinsaaret', allowance: 65, icon: '🇲🇭' },
	{ name: 'Martinique', allowance: 55, icon: '🇲🇶' },
	{ name: 'Mauritania', allowance: 52, icon: '🇲🇷' },
	{ name: 'Mauritius', allowance: 53, icon: '🇲🇺' },
	{ name: 'Meksiko', allowance: 81, icon: '🇲🇽' },
	{ name: 'Mikronesia', allowance: 59, icon: '🇫🇲' },
	{ name: 'Moldova', allowance: 73, icon: '🇲🇩' },
	{ name: 'Monaco', allowance: 92, icon: '🇲🇨' },
	{ name: 'Mongolia', allowance: 42, icon: '🇲🇳' },
	{ name: 'Montenegro', allowance: 66, icon: '🇲🇪' },
	{ name: 'Mosambik', allowance: 53, icon: '🇲🇿' },
	{ name: 'Myanmar', allowance: 58, icon: '🇲🇲' },
	{ name: 'Namibia', allowance: 36, icon: '🇳🇦' },
	{ name: 'Neitsytsaaret', allowance: 64, icon: '🇻🇮' },
	{ name: 'Nepal', allowance: 51, icon: '🇳🇵' },
	{ name: 'Nicaragua', allowance: 51, icon: '🇳🇮' },
	{ name: 'Niger', allowance: 50, icon: '🇳🇪' },
	{ name: 'Nigeria', allowance: 78, icon: '🇳🇬' },
	{ name: 'Norja', allowance: 70, icon: '🇳🇴' },
	{ name: 'Norsunluurannikko', allowance: 80, icon: '🇨🇮' },
	{ name: 'Oman', allowance: 74, icon: '🇴🇲' },
	{ name: 'Pakistan', allowance: 29, icon: '🇵🇰' },
	{ name: 'Palau', allowance: 99, icon: '🇵🇼' },
	{ name: 'Palestiinalaisalue', allowance: 76, icon: '🇵🇸' },
	{ name: 'Panama', allowance: 61, icon: '🇵🇦' },
	{ name: 'Papua-Uusi-Guinea', allowance: 76, icon: '🇵🇬' },
	{ name: 'Paraguay', allowance: 36, icon: '🇵🇾' },
	{ name: 'Peru', allowance: 52, icon: '🇵🇪' },
	{ name: 'Pohjois-Makedonia', allowance: 64, icon: '🇲🇰' },
	{ name: 'Portugali', allowance: 70, icon: '🇵🇹' },
	{ name: 'Puerto Rico', allowance: 70, icon: '🇵🇷' },
	{ name: 'Puola', allowance: 72, icon: '🇵🇱' },
	{ name: 'Qatar', allowance: 78, icon: '🇶🇦' },
	{ name: 'Ranska', allowance: 78, icon: '🇫🇷' },
	{ name: 'Romania', allowance: 68, icon: '🇷🇴' },
	{ name: 'Ruanda', allowance: 37, icon: '🇷🇼' },
	{ name: 'Ruotsi', allowance: 64, icon: '🇸🇪' },
	{ name: 'Saint Kitts ja Nevis', allowance: 68, icon: '🇰🇳' },
	{ name: 'Saint Lucia', allowance: 86, icon: '🇱🇨' },
	{ name: 'Saint Vincent ja Grenadiinit', allowance: 85, icon: '🇻🇨' },
	{ name: 'Saksa', allowance: 76, icon: '🇩🇪' },
	{ name: 'Salomonsaaret', allowance: 63, icon: '🇸🇧' },
	{ name: 'Sambia', allowance: 55, icon: '🇿🇲' },
	{ name: 'Samoa', allowance: 61, icon: '🇼🇸' },
	{ name: 'San Marino', allowance: 59, icon: '🇸🇲' },
	{ name: 'São Tomé ja Príncipe', allowance: 102, icon: '🇸🇹' },
	{ name: 'Saudi-Arabia', allowance: 80, icon: '🇸🇦' },
	{ name: 'Senegal', allowance: 58, icon: '🇸🇳' },
	{ name: 'Serbia', allowance: 75, icon: '🇷🇸' },
	{ name: 'Seychellit', allowance: 87, icon: '🇸🇨' },
	{ name: 'Sierra Leone', allowance: 47, icon: '🇸🇱' },
	{ name: 'Singapore', allowance: 79, icon: '🇸🇬' },
	{ name: 'Slovakia', allowance: 79, icon: '🇸🇰' },
	{ name: 'Slovenia', allowance: 72, icon: '🇸🇮' },
	{ name: 'Somalia', allowance: 86, icon: '🇸🇴' },
	{ name: 'Sri Lanka', allowance: 29, icon: '🇱🇰' },
	{ name: 'Sudan', allowance: 83, icon: '🇸🇩' },
	{ name: 'Suriname', allowance: 78, icon: '🇸🇷' },
	{ name: 'Sveitsi', allowance: 93, icon: '🇨🇭' },
	{ name: 'Syyria', allowance: 91, icon: '🇸🇾' },
	{ name: 'Tadžikistan', allowance: 35, icon: '🇹🇯' },
	{ name: 'Taiwan', allowance: 69, icon: '🇹🇼' },
	{ name: 'Tansania', allowance: 54, icon: '🇹🇿' },
	{ name: 'Tanska', allowance: 79, icon: '🇩🇰' },
	{ name: 'Thaimaa', allowance: 63, icon: '🇹🇭' },
	{ name: 'Togo', allowance: 58, icon: '🇹🇬' },
	{ name: 'Tonga', allowance: 62, icon: '🇹🇴' },
	{ name: 'Trinidad ja Tobago', allowance: 83, icon: '🇹🇹' },
	{ name: 'Tšad', allowance: 47, icon: '🇹🇩' },
	{ name: 'Tšekki', allowance: 89, icon: '🇨🇿' },
	{ name: 'Tunisia', allowance: 61, icon: '🇹🇳' },
	{ name: 'Turkki', allowance: 35, icon: '🇹🇷' },
	{ name: 'Turkmenistan', allowance: 92, icon: '🇹🇲' },
	{ name: 'Uganda', allowance: 49, icon: '🇺🇬' },
	{ name: 'Ukraina', allowance: 64, icon: '🇺🇦' },
	{ name: 'Unkari', allowance: 69, icon: '🇭🇺' },
	{ name: 'Uruguay', allowance: 59, icon: '🇺🇾' },
	{ name: 'Uusi-Seelanti', allowance: 74, icon: '🇳🇿' },
	{ name: 'Uzbekistan', allowance: 32, icon: '🇺🇿' },
	{ name: 'Valko-Venäjä', allowance: 63, icon: '🇧🇾' },
	{ name: 'Vanuatu', allowance: 70, icon: '🇻🇺' },
	{ name: 'Venezuela', allowance: 102, icon: '🇻🇪' },
	{ name: 'Venäjä', allowance: 66, icon: '🇷🇺' },
	{ name: 'Vietnam', allowance: 69, icon: '🇻🇳' },
	{ name: 'Viro', allowance: 75, icon: '🇪🇪' },
	{ name: 'Yhdysvallat', allowance: 89, icon: '🇺🇸' },
	{ name: 'Zimbabwe', allowance: 102, icon: '🇿🇼' },
	{ name: 'Maat, joita ei ole erikseen mainittu', allowance: 52, icon: '🌍' }
] as const;

export type DailyAllowance = (typeof dailyAllowances)[number];
